version: '3.9'

volumes:
  postgres_data: { }
  pgadmin-data: { }
  media_data: { }


services:
  app:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    env_file:
      - .env
    depends_on:
      - postgres
    profiles:
      - full_dev
    command: /start.sh
    container_name: app
    stdin_open: true
    tty: true
    volumes:
      - /var/www/static/:/var/www/static/
      - media_data:/var/www/media/
   
  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    profiles:
      - full_dev
      - local_dev
    container_name: postgres

  rabbitmq:
    image: "rabbitmq:3.9"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq


  celery:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    profiles:
      - full_dev
    command: celery --app core.celery_app worker --loglevel info --concurrency 4
    container_name: celery
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

  flower:
    image: local
    build: .
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    command: celery --broker=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672// flower
    container_name: flower
    depends_on:
      - rabbitmq
      - postgres
      - celery
    ports:
      - '5555:5555'
    stdin_open: true
    tty: true

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
      - /var/www/static/:/var/www/static/
