# Generated by Django 4.2.7 on 2023-11-09 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profession",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="title",
            new_name="name",
        ),
    ]
