# Generated by Django 4.2.7 on 2023-11-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0002_rename_title_profession_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profession",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="approved"),
        ),
        migrations.AddField(
            model_name="service",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="approved"),
        ),
        migrations.AlterField(
            model_name="profession",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="title"),
        ),
    ]
