# Generated by Django 4.2.7 on 2023-11-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0004_alter_profession_name_alter_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profession",
            name="services",
            field=models.ManyToManyField(related_name="professions", to="expert.service"),
        ),
        migrations.AlterField(
            model_name="profession",
            name="name",
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name="name"),
        ),
    ]
