# Generated by Django 4.2.7 on 2023-11-15 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0004_profession_services_alter_profession_name_and_more"),
        ("expert", "0005_profession_services_alter_profession_name_and_more"),
    ]

    operations = []
