# Generated by Django 4.2.7 on 2023-11-09 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.article")),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.article")),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ContributionLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.contribution"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ContributionImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.contribution"),
                ),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.image")),
            ],
        ),
        migrations.CreateModel(
            name="ContributionFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.contribution"),
                ),
                ("file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.file")),
            ],
        ),
        migrations.CreateModel(
            name="ContributionDislike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.contribution"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.comment")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CommentImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.comment")),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.image")),
            ],
        ),
        migrations.CreateModel(
            name="CommentFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.comment")),
                ("file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.file")),
            ],
        ),
        migrations.CreateModel(
            name="CommentDislike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.comment")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ArticleLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.article")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.article")),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.image")),
            ],
        ),
        migrations.CreateModel(
            name="ArticleFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.article")),
                ("file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.file")),
            ],
        ),
        migrations.CreateModel(
            name="ArticleDislike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.article")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
