# Generated by Django 4.2.7 on 2023-12-21 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("files", "0002_initial"),
        ("expert", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="post",
            name="country",
            field=models.ManyToManyField(blank=True, related_name="post_countries", to="cities_light.country"),
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="post_images", to="files.image"),
        ),
        migrations.AddField(
            model_name="post",
            name="professional_tags",
            field=models.ManyToManyField(blank=True, related_name="professional_tags", to="expert.profession"),
        ),
        migrations.AddField(
            model_name="contribution",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="contribution",
            name="dislikes",
            field=models.ManyToManyField(blank=True, related_name="contribution_dislikes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="contribution",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="contribution_images", to="files.image"),
        ),
        migrations.AddField(
            model_name="contribution",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="contribution_likes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="contribution",
            name="post",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.post"),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="content.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="content.post"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "post", "reaction_type")},
        ),
    ]
