# Generated by Django 4.2.7 on 2023-12-11 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
        ("files", "0001_initial"),
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="contribution",
            name="dislikes",
            field=models.ManyToManyField(blank=True, related_name="contribution_dislikes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="contribution",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="contribution_images", to="files.image"),
        ),
        migrations.AddField(
            model_name="contribution",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="contribution_likes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.article"),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="comment",
            name="dislikes",
            field=models.ManyToManyField(blank=True, related_name="comment_dislikes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="comment",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="comment_images", to="files.image"),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="comment_likes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="article",
            name="dislikes",
            field=models.ManyToManyField(blank=True, related_name="article_dislikes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="article",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="article_images", to="files.image"),
        ),
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="article_likes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="article",
            name="professional_tags",
            field=models.ManyToManyField(blank=True, related_name="professional_tags", to="expert.profession"),
        ),
    ]
