# Generated by Django 4.2.7 on 2023-12-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="helpful_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="not_helpful_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
