# Generated by Django 4.2.7 on 2023-12-12 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0002_initial"),
        ("expert", "0001_initial"),
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Post",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="article",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="contribution",
            old_name="article",
            new_name="post",
        ),
    ]
