# Generated by Django 4.2.7 on 2023-12-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_comment_helpful_count_comment_not_helpful_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="helpful_count",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="not_helpful_count",
        ),
        migrations.CreateModel(
            name="UserCommentVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("helpful", models.BooleanField()),
                ("comment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.comment")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "comment")},
            },
        ),
    ]
