# Generated by Django 4.2.7 on 2023-12-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("content", "0003_rename_article_post_rename_article_comment_post_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="country",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cities_light.country"),
        ),
    ]
