# Generated by Django 4.2.7 on 2023-12-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_remove_comment_helpful_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_parent",
            field=models.BooleanField(default=True),
        ),
    ]
