# Generated by Django 4.2.7 on 2023-12-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_initial"),
        ("content", "0004_remove_post_dislikes_remove_post_likes_post_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, null=True, related_name="article_images", to="files.image"),
        ),
    ]
