# Generated by Django 4.2.7 on 2023-12-27 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0005_comment_is_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="images",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="likes",
        ),
        migrations.AddField(
            model_name="comment",
            name="contribution",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="content.contribution"
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="helpful_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ContributionVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("helpful", models.BooleanField()),
                (
                    "contribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="content.contribution"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "contribution")},
            },
        ),
    ]
