# Generated by Django 4.2.7 on 2023-12-27 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_comment_helpful_count_comment_not_helpful_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="helpful_count",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="not_helpful_count",
        ),
    ]
