# Generated by Django 4.2.7 on 2023-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("files", "0002_initial"),
        ("content", "0007_alter_post_content_remove_post_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="country",
            field=models.ManyToManyField(blank=True, related_name="post_countries", to="cities_light.country"),
        ),
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="post_images", to="files.image"),
        ),
    ]
