# Generated by Django 4.2.7 on 2023-12-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_initial"),
        ("content", "0010_alter_post_country_remove_post_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="images",
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="post_images", to="files.image"),
        ),
    ]
