# Generated by Django 4.2.7 on 2023-12-20 10:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_remove_post_reactions_remove_post_worldwide_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="content.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(10000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=10000, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
    ]
