# Generated by Django 4.2.7 on 2024-01-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0002_category"),
        ("content", "0011_remove_post_images_post_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to="expert.category"
            ),
        ),
    ]
