# Generated by Django 4.2.7 on 2024-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_remove_post_images_post_images"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributionvote",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="contributionvote",
            name="contribution",
        ),
        migrations.RemoveField(
            model_name="contributionvote",
            name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="contribution",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_contribution",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Contribution",
        ),
        migrations.DeleteModel(
            name="ContributionVote",
        ),
    ]
