# Generated by Django 4.2.7 on 2023-12-21 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_comment_author_alter_post_author"),
        ("content", "0012_post_updated_date"),
    ]

    operations = []
