# Generated by Django 4.2.7 on 2024-01-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0002_category"),
        ("content", "0012_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(related_name="post_category", to="expert.category"),
        ),
    ]
