# Generated by Django 4.2.7 on 2024-01-08 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_alter_contributionvote_unique_together_and_more"),
        ("content", "0013_remove_post_category_post_category"),
    ]

    operations = []
