# Generated by Django 4.2.7 on 2024-01-23 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_remove_post_professional_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
