# Generated by Django 4.2.7 on 2024-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_reaction_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
