# Generated by Django 4.2.7 on 2024-01-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_postimage"),
        ("content", "0017_alter_reaction_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="images",
        ),
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="files.postimage"
            ),
        ),
    ]
