# Generated by Django 4.2.7 on 2024-01-29 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0017_alter_reaction_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="mentions",
            field=models.ManyToManyField(blank=True, related_name="comment_mentions", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="post",
            name="mentions",
            field=models.ManyToManyField(blank=True, related_name="post_mentions", to=settings.AUTH_USER_MODEL),
        ),
    ]
