# Generated by Django 4.2.7 on 2024-01-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_postimage"),
        ("content", "0018_remove_post_images_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="files.postimage"
            ),
        ),
    ]
