# Generated by Django 4.2.7 on 2024-01-29 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0018_comment_mentions_post_mentions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="mentions",
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mentioned_users",
                    models.ManyToManyField(related_name="mentioned_in_mentions", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
