# Generated by Django 4.2.7 on 2024-01-29 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0019_remove_post_mentions_mention"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mention",
            name="mentioned_users",
        ),
        migrations.AddField(
            model_name="mention",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_mentions",
                to="content.comment",
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="mentioned_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentioned_in_mentions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_mentions",
                to="content.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="mentions",
            field=models.ManyToManyField(blank=True, related_name="post_mentions", to=settings.AUTH_USER_MODEL),
        ),
    ]
