# Generated by Django 4.2.7 on 2024-01-29 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0020_remove_mention_mentioned_users_mention_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mention",
            name="mentioned_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentioned_in_mentions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
