# Generated by Django 4.2.7 on 2024-01-30 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_remove_post_post_image"),
        ("content", "0022_remove_comment_mentions_remove_post_mentions_and_more"),
    ]

    operations = []
