# Generated by Django 4.2.7 on 2024-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0023_merge_20240130_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="vote_helpful_state",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="vote_not_helpful_state",
            field=models.BooleanField(default=False),
        ),
    ]
