# Generated by Django 4.2.7 on 2024-02-07 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_comment_vote_helpful_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="vote_helpful_state",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="vote_not_helpful_state",
        ),
    ]
