# Generated by Django 4.2.7 on 2024-02-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('verification_code_hashed', models.CharField(blank=True, max_length=128)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
