# Generated by Django 4.2.7 on 2023-12-13 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileextended",
            name="about_my_self_ext",
        ),
        migrations.RemoveField(
            model_name="userprofileextended",
            name="resume",
        ),
    ]
