# Generated by Django 4.2.7 on 2023-12-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0001_initial"),
        ("files", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileextended",
            name="profession",
        ),
        migrations.AlterField(
            model_name="userprofileextended",
            name="resume",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="files.file"
            ),
        ),
        migrations.AddField(
            model_name="userprofileextended",
            name="profession",
            field=models.ManyToManyField(to="expert.profession"),
        ),
    ]
