# Generated by Django 4.2.7 on 2023-11-23 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_twilio_verification_sid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="twilio_verified",
            new_name="twilio_phone_verified",
        ),
    ]
