# Generated by Django 4.2.7 on 2024-01-10 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_userprofile_phone_verified_request_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="facebook",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(limit_value=200)],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instagram",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    django.core.validators.MaxLengthValidator(limit_value=50),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(limit_value=200)],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    django.core.validators.MaxLengthValidator(limit_value=50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="about_my_self",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    django.core.validators.MaxLengthValidator(limit_value=500),
                ],
            ),
        ),
    ]
