# Generated by Django 4.2.7 on 2023-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofileextended_about_my_self_ext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted_user',
            field=models.BooleanField(default=False),
        ),
    ]
