# Generated by Django 4.2.7 on 2024-01-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0002_category"),
        ("users", "0003_userprofile_facebook_userprofile_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileextended",
            name="profession",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="expert.profession"
            ),
        ),
        migrations.AlterField(
            model_name="userprofileextended",
            name="service",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="expert.service"
            ),
        ),
    ]
