# Generated by Django 4.2.7 on 2023-11-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_twilio_verified_userprofile_twilio_phone_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_verified_request_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
