# Generated by Django 4.2.7 on 2023-12-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0004_remove_image_image_name_alter_image_image"),
        ("users", "0004_userprofile_phone_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="files.image"
            ),
        ),
    ]
