# Generated by Django 4.2.7 on 2023-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_username_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_full_name_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
