# Generated by Django 4.2.7 on 2024-01-15 10:36

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="facebook",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(limit_value=200)],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="instagram",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    django.core.validators.MaxLengthValidator(limit_value=50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(limit_value=200)],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=15, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telegram",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    django.core.validators.MaxLengthValidator(limit_value=50),
                ],
            ),
        ),
    ]
