# Generated by Django 4.2.7 on 2023-11-15 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_email_alter_user_first_name_and_more"),
        ("users", "0005_alter_userprofile_phone_number"),
    ]

    operations = []
