# Generated by Django 4.2.7 on 2024-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_userprofile_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="facebook_is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instagram_is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
