# Generated by Django 4.2.7 on 2023-12-21 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_last_full_name_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                default="Anonim User",
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    django.core.validators.MaxLengthValidator(limit_value=50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="anonim_user_1",
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    django.core.validators.MaxLengthValidator(limit_value=32),
                ],
            ),
        ),
    ]
