# Generated by Django 4.2.7 on 2023-12-21 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_userprofileextended_profession_and_more"),
        ("users", "0007_alter_user_full_name_alter_user_username"),
    ]

    operations = []
