# Generated by Django 4.2.7 on 2024-01-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0002_category"),
        ("users", "0008_remove_userprofileextended_profession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileextended",
            name="profession",
            field=models.ManyToManyField(blank=True, to="expert.profession"),
        ),
        migrations.AlterField(
            model_name="userprofileextended",
            name="service",
            field=models.ManyToManyField(blank=True, to="expert.service"),
        ),
    ]
