# Generated by Django 4.2.7 on 2024-01-19 13:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_userprofileextended_profession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=14, null=True, region=None, unique=True
            ),
        ),
    ]
