# Generated by Django 4.2.7 on 2024-01-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_remove_post_professional_tags"),
        ("users", "0010_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_comments",
            field=models.ManyToManyField(related_name="user_comments", to="content.comment"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_posts",
            field=models.ManyToManyField(related_name="user_posts", to="content.post"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_reactions",
            field=models.ManyToManyField(related_name="user_reactions", to="content.reaction"),
        ),
    ]
