# Generated by Django 4.2.7 on 2024-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_alter_reaction_creation_date"),
        ("users", "0011_userprofile_last_comments_userprofile_last_posts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="last_reactions",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_reacted_posts",
            field=models.ManyToManyField(related_name="last_reacted_user_posts", to="content.post"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_comments",
            field=models.ManyToManyField(related_name="last_user_comments", to="content.comment"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_posts",
            field=models.ManyToManyField(related_name="last_user_posts", to="content.post"),
        ),
    ]
