# Generated by Django 4.2.7 on 2024-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_alter_reaction_creation_date"),
        ("users", "0012_remove_userprofile_last_reactions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_contributions",
            field=models.ManyToManyField(related_name="last_user_contributions", to="content.comment"),
        ),
    ]
