# Generated by Django 4.2.7 on 2024-01-26 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_userprofile_last_contributions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="saved_comments",
        ),
    ]
