# Generated by Django 4.2.7 on 2024-01-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0023_merge_20240130_0939"),
        ("users", "0014_remove_userprofile_saved_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_comments",
            field=models.ManyToManyField(blank=True, related_name="last_user_comments", to="content.comment"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_contributions",
            field=models.ManyToManyField(blank=True, related_name="last_user_contributions", to="content.comment"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_posts",
            field=models.ManyToManyField(blank=True, related_name="last_user_posts", to="content.post"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_reacted_posts",
            field=models.ManyToManyField(blank=True, related_name="last_reacted_user_posts", to="content.post"),
        ),
    ]
