# Generated by Django 4.2.7 on 2024-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_accounts_are_visible',
            field=models.BooleanField(default=True),
        ),
    ]
