# Generated by Django 4.2.7 on 2023-12-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatedCity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translated_city",
                        to="cities_light.city",
                    ),
                ),
            ],
        ),
    ]
