# Generated by Django 4.2.7 on 2023-12-21 20:42

import apps.files.models.image
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.ImageField(null=True, upload_to=apps.files.models.image.universal_file_path_builder)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(null=True, upload_to=apps.files.models.image.universal_file_path_builder)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
