# Generated by Django 4.2.7 on 2023-12-13 11:46

import apps.files.models.image
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file_name",
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.ImageField(null=True, upload_to=apps.files.models.image.universal_file_path_builder),
        ),
    ]
