# Generated by Django 4.2.7 on 2023-11-23 10:13

import apps.files.models.image
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_alter_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_name",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to=apps.files.models.image.universal_file_path_builder),
        ),
    ]
