# Generated by Django 4.2.7 on 2024-01-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_remove_post_post_image"),
        ("files", "0003_postimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="post",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="content.post"),
        ),
    ]
